[package]
name = "journal"
version = "0.1.2"
edition = "2018"
authors = ["raph"]

[dependencies]
cbor-codec = ">= 0.7.1"
uuid = "0.6"

[dependencies.sodiumoxide]
version = "^0.2"
default-features = false
features = ["std"]

[lib]
name = "morphingidentity"
path = "src/morphingidentity/lib.rs"
